
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LLAVE_IZQ = 2;
  public static final int DECIMAL = 8;
  public static final int COMA = 4;
  public static final int LLAVE_DER = 3;
  public static final int DOSPUNTOS = 5;
  public static final int STRING = 9;
  public static final int EOF = 0;
  public static final int COR_IZQ = 7;
  public static final int error = 1;
  public static final int COR_DER = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LLAVE_IZQ",
  "LLAVE_DER",
  "COMA",
  "DOSPUNTOS",
  "COR_DER",
  "COR_IZQ",
  "DECIMAL",
  "STRING"
  };
    
}

